name: bincheck

on: push

permissions:
  contents: read

jobs:

  darwin:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: cd build/release/bincheck && ./test-macos v23.2.0-alpha.5 af2cdcea915f024eae56aee7b3dee8794cbc44e1
